CREATE SCHEMA blazorserverapp AUTHORIZATION blazorserverapp_user;
CREATE TABLE blazorserverapp."AspNetUsers" (
	"Id" text NOT NULL,
	"UserName" varchar(256) NULL,
	"NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NULL,
	"NormalizedEmail" varchar(256) NULL,
	"EmailConfirmed" bool NOT NULL,
	"PasswordHash" text NULL,
	"SecurityStamp" text NULL,
	"ConcurrencyStamp" text NULL,
	"PhoneNumber" text NULL,
	"PhoneNumberConfirmed" bool NOT NULL,
	"TwoFactorEnabled" bool NOT NULL,
	"LockoutEnd" timestamptz NULL,
	"LockoutEnabled" bool NOT NULL,
	"AccessFailedCount" int4 NOT NULL,
	CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);
CREATE INDEX "EmailIndex" ON blazorserverapp."AspNetUsers" USING btree ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON blazorserverapp."AspNetUsers" USING btree ("NormalizedUserName");

-----------------------------------------------------------------------------------------------------------------------------

CREATE TABLE blazorserverapp."AspNetRoles" (
	"Id" text NOT NULL,
	"Name" varchar(256) NULL,
	"NormalizedName" varchar(256) NULL,
	"ConcurrencyStamp" text NULL,
	CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "RoleNameIndex" ON blazorserverapp."AspNetRoles" USING btree ("NormalizedName");

-----------------------------------------------------------------------------------------------------------------------------
CREATE TABLE blazorserverapp."AspNetUserLogins" (
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text NULL,
	"UserId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
);
CREATE INDEX "IX_AspNetUserLogins_UserId" ON blazorserverapp."AspNetUserLogins" USING btree ("UserId");

ALTER TABLE blazorserverapp."AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES blazorserverapp."AspNetUsers"("Id") ON DELETE CASCADE;

-----------------------------------------------------------------------------------------------------------------------------

CREATE TABLE blazorserverapp."AspNetUserTokens" (
	"UserId" text NOT NULL,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text NULL,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

ALTER TABLE blazorserverapp."AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES blazorserverapp."AspNetUsers"("Id") ON DELETE CASCADE;

-----------------------------------------------------------------------------------------------------------------------------

CREATE TABLE blazorserverapp."AspNetUserRoles" (
	"UserId" text NOT NULL,
	"RoleId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId")
);
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON blazorserverapp."AspNetUserRoles" USING btree ("RoleId");

ALTER TABLE blazorserverapp."AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES blazorserverapp."AspNetRoles"("Id") ON DELETE CASCADE;
ALTER TABLE blazorserverapp."AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES blazorserverapp."AspNetUsers"("Id") ON DELETE CASCADE;

-----------------------------------------------------------------------------------------------------------------------------

CREATE TABLE blazorserverapp."AspNetRoleClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"RoleId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON blazorserverapp."AspNetRoleClaims" USING btree ("RoleId");

ALTER TABLE blazorserverapp."AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES blazorserverapp."AspNetRoles"("Id") ON DELETE CASCADE;

-----------------------------------------------------------------------------------------------------------------------------
CREATE TABLE blazorserverapp."AspNetUserClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_AspNetUserClaims_UserId" ON blazorserverapp."AspNetUserClaims" USING btree ("UserId");

ALTER TABLE blazorserverapp."AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES blazorserverapp."AspNetUsers"("Id") ON DELETE CASCADE;


-----------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE blazorserverapp.logauditoria;

CREATE TABLE blazorserverapp.logauditoria (
	logauditoriaid serial4 NOT NULL,
	usuario varchar(256) NOT NULL,
	tabela varchar(256) NOT NULL,
	operacao varchar(50) NOT NULL,
	dado jsonb NOT NULL,
	"data" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	iporigem varchar(45) NOT NULL
);